<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-DAL8TCK" failures="4" tests="6" name="Test(failed)(failed)" time="9.714" errors="0" timestamp="2025-08-05T19:42:28 IST">
  <testcase classname="com.WebTesting.TestNG.Basics.TestDemo5_Assertion" name="testSoftAssertion" time="0.009">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at com.WebTesting.TestNG.Basics.TestDemo5_Assertion.testSoftAssertion(TestDemo5_Assertion.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testSoftAssertion -->
  <testcase classname="com.WebTesting.TestNG.Basics.TestDemo6_HRMLoginValidation" name="testLogin" time="4.656">
    <failure type="java.lang.AssertionError" message="Login Fail expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Fail expected [true] but found [false]
at com.WebTesting.TestNG.Basics.TestDemo6_HRMLoginValidation.testLogin(TestDemo6_HRMLoginValidation.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testLogin -->
  <testcase classname="com.WebTesting.TestNG.Basics.TestDemo7_timeouts" name="testCase2" time="5.013">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.WebTesting.TestNG.Basics.TestDemo7_timeouts.testCase2() didn&amp;apos;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.WebTesting.TestNG.Basics.TestDemo7_timeouts.testCase2() didn't finish within the time-out 5000
at java.base/java.lang.Thread.sleep0(Native Method)
at java.base/java.lang.Thread.sleep(Thread.java:509)
at com.WebTesting.TestNG.Basics.TestDemo7_timeouts.testCase2(TestDemo7_timeouts.java:21)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 6 stack frames]]>
    </failure>
  </testcase> <!-- testCase2 -->
  <testcase classname="com.WebTesting.TestNG.Basics.TestDemo8_dependsOnMethod" name="registerTest" time="0.0"/>
  <testcase classname="com.WebTesting.TestNG.Basics.TestDemo8_dependsOnMethod" name="loginTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Fail as values are not equal expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Fail as values are not equal expected [true] but found [false]
at com.WebTesting.TestNG.Basics.TestDemo8_dependsOnMethod.loginTest(TestDemo8_dependsOnMethod.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.WebTesting.TestNG.Basics.TestDemo8_dependsOnMethod" name="logoutTest" time="0.0">
    <skipped/>
  </testcase> <!-- logoutTest -->
  <testcase classname="com.WebTesting.TestNG.Basics.TestDemo7_timeouts" name="testCase1" time="0.0">
    <ignored/>
  </testcase> <!-- testCase1 -->
  <testcase classname="com.WebTesting.TestNG.Basics.TestDemo5_Assertion" name="testHardAssertion" time="0.0">
    <ignored/>
  </testcase> <!-- testHardAssertion -->
</testsuite> <!-- Test(failed)(failed) -->
