<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-DAL8TCK" failures="0" tests="2" name="com.WebTesting.TestNG.Basics.TestDemo7_timeouts" time="10.023" errors="1" timestamp="2025-08-06T14:50:18 IST" skipped="0">
  <testcase classname="com.WebTesting.TestNG.Basics.TestDemo7_timeouts" name="testCase2" time="5.013">
    <error message="Method com.WebTesting.TestNG.Basics.TestDemo7_timeouts.testCase2() didn&#039;t finish within the time-out 5000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.WebTesting.TestNG.Basics.TestDemo7_timeouts.testCase2() didn't finish within the time-out 5000
at java.base/java.lang.Thread.sleep0(Native Method)
at java.base/java.lang.Thread.sleep(Thread.java:509)
at com.WebTesting.TestNG.Basics.TestDemo7_timeouts.testCase2(TestDemo7_timeouts.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- testCase2 -->
  <testcase classname="com.WebTesting.TestNG.Basics.TestDemo7_timeouts" name="testCase1" time="5.010"/>
</testsuite> <!-- com.WebTesting.TestNG.Basics.TestDemo7_timeouts -->
